/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vira;
import java.awt.HeadlessException;
import javax.swing.*;
import java.sql.*;
import java.text.DateFormat;
import javax.swing.table.*;
//import java.sql.
/**
 *
 * @author Archi3
 */
public class viewLaundry extends javax.swing.JFrame {
    String no_antrian, jenis_cucian, nama;
    int berat_cucian, harga_cucian, harga;
    //tanggal_masuk, tanggal_keluar
    String status, mauCari;
    Connection con;
    /**
     * Creates new form viewLaundry
     */
    public viewLaundry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAntrian = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBerat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        comboLaundry = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        boxPending = new javax.swing.JRadioButton();
        boxOut = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Transaksi Perusahaan Laundry");

        jLabel2.setText("No Antrian");

        jLabel3.setText("Nama");

        jLabel4.setText("Berat Cucian");

        txtBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBeratKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBeratKeyTyped(evt);
            }
        });

        jLabel5.setText("Status");

        txtTotal.setEnabled(false);

        comboLaundry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis", "Laundry", "Laundry + Setrika" }));
        comboLaundry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboLaundryItemStateChanged(evt);
            }
        });

        jLabel6.setText("Jenis Laundry");

        jLabel7.setText("Total");

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        boxPending.setText("Pending");
        boxPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPendingActionPerformed(evt);
            }
        });

        boxOut.setText("Checkout");
        boxOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxOutActionPerformed(evt);
            }
        });

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Menu Utama");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Report");

        jMenuItem3.setText("Report Pending");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem4.setText("Report Checkout");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boxPending)
                                .addGap(36, 36, 36)
                                .addComponent(boxOut))
                            .addComponent(txtBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboLaundry, javax.swing.GroupLayout.Alignment.LEADING, 0, 134, Short.MAX_VALUE)))
                        .addContainerGap(173, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(0, 120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(boxPending)
                            .addComponent(boxOut))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtBeratKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeratKeyPressed

    }//GEN-LAST:event_txtBeratKeyPressed

    private void txtBeratKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeratKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtBeratKeyTyped

    private void comboLaundryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboLaundryItemStateChanged
        // TODO add your handling code here:
        hargaLaundry();
    }//GEN-LAST:event_comboLaundryItemStateChanged

    private void boxPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPendingActionPerformed
        // TODO add your handling code here:
        boxOut.setSelected(false);
        boxPending.setSelected(true);
    }//GEN-LAST:event_boxPendingActionPerformed

    private void boxOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxOutActionPerformed
        // TODO add your handling code here:
        boxPending.setSelected(false);
        boxOut.setSelected(true);
    }//GEN-LAST:event_boxOutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tambahData();
        bersih();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        updateData();
        bersih();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        formPending fp = new formPending();
        fp.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        formCheck fc = new formCheck();
        fc.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewLaundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boxOut;
    private javax.swing.JRadioButton boxPending;
    private javax.swing.JComboBox<String> comboLaundry;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JTextField txtAntrian;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
    public void konekDatabase(){
        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Archi3\\Documents\\NetBeansProjects\\vira\\Access\\dataLaundry.mdb");
        }catch(ClassNotFoundException | SQLException e){
            System.err.println("Exception "+e.getMessage());
        }
    }
    public void hargaLaundry(){
        int pilihan = comboLaundry.getSelectedIndex();
        switch(pilihan){
            case 0:
                break;
            case 1:
                 harga = Integer.parseInt(txtBerat.getText());
                 harga = harga * 7000;
                 //JOptionPane.showMessageDialog(null, harga);
                 txtTotal.setText(String.valueOf(harga));
                 jenis_cucian = "Laundry";
                 break;
            case 2:
                harga = Integer.parseInt(txtBerat.getText()) * 10000;
                txtTotal.setText(String.valueOf(harga));
                jenis_cucian = "Laundry + Setrika";
        }
    }
    public void tambahData(){
        no_antrian = txtAntrian.getText();
        nama = txtNama.getText();
        berat_cucian = Integer.parseInt(txtBerat.getText());
        harga_cucian = Integer.parseInt(txtTotal.getText());
        //jenis_cucian;
        if(boxPending.isSelected() == true){
            status = "Pending";
        }else if(boxPending.isSelected() == false){
            status = "Checkout";
        }
        try{
            konekDatabase();
            Statement stmt = con.createStatement();
            String query = "INSERT INTO data_laundry VALUES ('"+no_antrian +"','"+nama+"')";
            String sql = "INSERT INTO detail_laundry VALUES ('"+ no_antrian +"',"
                    + "'"+jenis_cucian+"',"
                    + "'"+berat_cucian+"',"
                    + "'"+harga_cucian+"',"
                    + "'"+status+"')";
            stmt.executeUpdate(sql);
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data berhasil dimasukan");
        }catch(SQLException | HeadlessException e){
            
        }
    }
    public void bersih(){
        txtAntrian.setText("");
        txtNama.setText("");
        txtBerat.setText("");
        boxPending.setSelected(false);
        boxOut.setSelected(false);
        harga = 0;
        comboLaundry.setSelectedIndex(0);
        txtTotal.setText("");
    }
    public void hapusData(){
        konekDatabase();
        bersih();
        try{
            String cari = JOptionPane.showInputDialog("Masukan No Antrian");
            Statement stmt = con.createStatement();
            String sql = "DELETE FROM data_laundry WHERE no_antrian = '"+cari+"'";
            String query = "DELETE FROM detail_laundry WHERE no_antrian ='"+cari+"'";
            stmt.executeUpdate(sql);
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Terhapuskan");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void cariData(){
        konekDatabase();
        try{
            String cari = JOptionPane.showInputDialog("Masukan no antrian");
            Statement stmt = con.createStatement();
            String query = "SELECT * from detail_laundry where no_antrian = '"+cari+"'";
            String sql = "SELECT * from data_laundry WHERE no_antrian like '"+cari+"'";
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                txtAntrian.setText(rs.getString(1));
                txtNama.setText(rs.getString(2));
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
            ResultSet rs1 = stmt.executeQuery(query);
            if(rs1.next()){
                txtBerat.setText(rs1.getString(3));
                if ("Pending".equals(rs1.getString(5))){
                    boxPending.setSelected(true);
                }else if("Checkout".equals(rs1.getString(5))){
                    boxOut.setSelected(true);
                }
                txtTotal.setText(rs1.getString(4));
                if("Laundry".equals(rs1.getString(2))){
                    comboLaundry.setSelectedIndex(1);
                }else{
                    comboLaundry.setSelectedIndex(2);
                }
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void updateData(){
        konekDatabase();
        try{
            no_antrian = txtAntrian.getText();
            nama = txtNama.getText();
            berat_cucian = Integer.parseInt(txtBerat.getText());
            harga_cucian = Integer.parseInt(txtTotal.getText());
             //jenis_cucian;
            if(boxPending.isSelected() == true){
            status = "Pending";
            }else if(boxPending.isSelected() == false){
            status = "Checkout";
             }
            Statement stmt = con.createStatement();
            String sql = "UPDATE detail_laundry set no_antrian = '"+no_antrian+"', "
                    + "jenis_cucian = '"+jenis_cucian+"',"
                    + "berat_cucian = '"+berat_cucian+"',"
                    + "harga_cucian = '"+harga_cucian+"',"
                    + "status_cucian = '"+status+"' where no_antrian = '"+no_antrian+"'";
            stmt.executeUpdate(sql);
        }catch(NumberFormatException | SQLException e){
            
        }
    }
}
